// Copyright 2024-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { suite } from "node:test";
import { createSimpleTestFileSkip, testSimpleTestFile } from "./testing.js";
import { getSimpleTestFiles } from "@bufbuild/cel-spec/testdata/simple.js";
import { getTestRegistry } from "@bufbuild/cel-spec/testdata/registry.js";

const files = getSimpleTestFiles();

const shouldSkip = createSimpleTestFileSkip(files, [
  ["bindings_ext"],
  ["block_ext"],
  ["dynamic", "int32", "field_assign_proto2_range"],
  ["dynamic", "int32", "field_assign_proto3_range"],
  ["dynamic", "uint32", "field_assign_proto2_range"],
  ["dynamic", "uint32", "field_assign_proto3_range"],
  ["dynamic", "float", "field_assign_proto2_range"],
  ["dynamic", "float", "field_assign_proto3_range"],
  ["dynamic", "double", "field_assign_proto2_range"],
  ["dynamic", "double", "field_assign_proto3_range"],
  ["dynamic", "uint32", "field_read_proto2_zero"],
  ["dynamic", "uint64", "field_read_proto2_zero"],
  ["dynamic", "float", "literal_not_double"],
  ["dynamic", "list", "literal"],
  ["dynamic", "list", "literal_no_field_access"],
  ["dynamic", "list", "literal_empty"],
  ["dynamic", "list", "var"],
  ["dynamic", "list", "field_assign_proto2"],
  ["dynamic", "list", "field_assign_proto2_empty"],
  ["dynamic", "list", "field_read_proto2"],
  ["dynamic", "list", "field_read_proto2_empty"],
  ["dynamic", "list", "field_read_proto2_unset"],
  ["dynamic", "list", "field_assign_proto3"],
  ["dynamic", "list", "field_assign_proto3_empty"],
  ["dynamic", "list", "field_read_proto3"],
  ["dynamic", "list", "field_read_proto3_empty"],
  ["dynamic", "list", "field_read_proto3_unset"],
  ["dynamic", "struct", "literal"],
  ["dynamic", "struct", "literal_no_field_access"],
  ["dynamic", "struct", "literal_empty"],
  ["dynamic", "struct", "var"],
  ["dynamic", "struct", "field_assign_proto2"],
  ["dynamic", "struct", "field_assign_proto2_empty"],
  ["dynamic", "struct", "field_read_proto2"],
  ["dynamic", "struct", "field_read_proto2_empty"],
  ["dynamic", "struct", "field_read_proto2_unset"],
  ["dynamic", "struct", "field_assign_proto3"],
  ["dynamic", "struct", "field_assign_proto3_empty"],
  ["dynamic", "struct", "field_read_proto3"],
  ["dynamic", "struct", "field_read_proto3_empty"],
  ["dynamic", "struct", "field_read_proto3_unset"],
  ["dynamic", "value_null", "literal"],
  ["dynamic", "value_null", "var"],
  ["dynamic", "value_null", "field_assign_proto2"],
  ["dynamic", "value_null", "field_read_proto2"],
  ["dynamic", "value_null", "field_assign_proto3"],
  ["dynamic", "value_null", "field_read_proto3"],
  ["dynamic", "value_number", "literal"],
  ["dynamic", "value_number", "literal_zero"],
  ["dynamic", "value_number", "var"],
  ["dynamic", "value_number", "field_assign_proto2"],
  ["dynamic", "value_number", "field_assign_proto2_zero"],
  ["dynamic", "value_number", "field_read_proto2"],
  ["dynamic", "value_number", "field_read_proto2_zero"],
  ["dynamic", "value_number", "field_assign_proto3"],
  ["dynamic", "value_number", "field_assign_proto3_zero"],
  ["dynamic", "value_number", "field_read_proto3"],
  ["dynamic", "value_number", "field_read_proto3_zero"],
  ["dynamic", "value_string", "literal"],
  ["dynamic", "value_string", "literal_empty"],
  ["dynamic", "value_string", "var"],
  ["dynamic", "value_string", "field_assign_proto2"],
  ["dynamic", "value_string", "field_assign_proto2_empty"],
  ["dynamic", "value_string", "field_read_proto2"],
  ["dynamic", "value_string", "field_read_proto2_zero"],
  ["dynamic", "value_string", "field_assign_proto3"],
  ["dynamic", "value_string", "field_assign_proto3_empty"],
  ["dynamic", "value_string", "field_read_proto3"],
  ["dynamic", "value_string", "field_read_proto3_zero"],
  ["dynamic", "value_bool", "literal"],
  ["dynamic", "value_bool", "literal_false"],
  ["dynamic", "value_bool", "var"],
  ["dynamic", "value_bool", "field_read_proto2_false"],
  ["dynamic", "value_bool", "field_read_proto2"],
  ["dynamic", "value_bool", "field_read_proto3"],
  ["dynamic", "value_bool", "field_read_proto3_false"],
  ["dynamic", "value_bool", "field_assign_proto2"],
  ["dynamic", "value_bool", "field_assign_proto2_false"],
  ["dynamic", "value_bool", "field_assign_proto3"],
  ["dynamic", "value_bool", "field_assign_proto3_false"],
  ["dynamic", "value_struct", "literal"],
  ["dynamic", "value_struct", "literal_no_field_access"],
  ["dynamic", "value_struct", "literal_empty"],
  ["dynamic", "value_struct", "var"],
  ["dynamic", "value_struct", "field_assign_proto2"],
  ["dynamic", "value_struct", "field_assign_proto2_empty"],
  ["dynamic", "value_struct", "field_read_proto2"],
  ["dynamic", "value_struct", "field_read_proto2_empty"],
  ["dynamic", "value_struct", "field_assign_proto3"],
  ["dynamic", "value_struct", "field_assign_proto3_empty"],
  ["dynamic", "value_struct", "field_read_proto3"],
  ["dynamic", "value_struct", "field_read_proto3_empty"],
  ["dynamic", "value_list", "literal"],
  ["dynamic", "value_list", "literal_no_field_access"],
  ["dynamic", "value_list", "literal_empty"],
  ["dynamic", "value_list", "var"],
  ["dynamic", "value_list", "field_assign_proto2"],
  ["dynamic", "value_list", "field_assign_proto2_empty"],
  ["dynamic", "value_list", "field_read_proto2"],
  ["dynamic", "value_list", "field_read_proto2_empty"],
  ["dynamic", "value_list", "field_assign_proto3"],
  ["dynamic", "value_list", "field_assign_proto3_empty"],
  ["dynamic", "value_list", "field_read_proto3"],
  ["dynamic", "value_list", "field_read_proto3_empty"],
  ["dynamic", "any", "literal"],
  ["dynamic", "any", "literal_no_field_access"],
  ["dynamic", "any", "literal_empty"],
  ["dynamic", "any", "var"],
  ["dynamic", "any", "field_assign_proto2"],
  ["dynamic", "any", "field_read_proto2"],
  ["dynamic", "any", "field_assign_proto3"],
  ["dynamic", "any", "field_read_proto3"],
  ["dynamic", "complex", "any_list_map"],
  ["encoders_ext", "encode", "hello"],
  ["encoders_ext", "decode", "hello"],
  ["encoders_ext", "decode", "hello_without_padding"],
  ["encoders_ext", "round_trip", "hello"],
  ["enums", "legacy_proto2", "field_type"],
  ["enums", "legacy_proto2", "assign_standalone_name"],
  ["enums", "legacy_proto2", "assign_standalone_int"],
  ["enums", "legacy_proto2", "assign_standalone_int_too_big"],
  ["enums", "legacy_proto2", "assign_standalone_int_too_neg"],
  ["enums", "legacy_proto3", "select"],
  ["enums", "legacy_proto3", "select_big"],
  ["enums", "legacy_proto3", "select_neg"],
  ["enums", "legacy_proto3", "field_type"],
  ["enums", "legacy_proto3", "assign_standalone_name"],
  ["enums", "legacy_proto3", "assign_standalone_int"],
  ["enums", "legacy_proto3", "assign_standalone_int_big"],
  ["enums", "legacy_proto3", "assign_standalone_int_neg"],
  ["enums", "legacy_proto3", "assign_standalone_int_too_big"],
  ["enums", "legacy_proto3", "assign_standalone_int_too_neg"],
  // Enums began as Ints but were changed to have types and reverted back again: https://github.com/google/cel-spec/pull/321
  ["enums", "strong_proto2"],
  ["enums", "strong_proto3"],
  [
    "fields",
    "qualified_identifier_resolution",
    "map_value_repeat_key_heterogeneous",
  ],
  ["fields", "quoted_map_fields"],
  ["math_ext", "greatest_int_result"],
  ["math_ext", "greatest_double_result"],
  ["math_ext", "greatest_uint_result"],
  ["math_ext", "least_int_result"],
  ["math_ext", "least_double_result"],
  ["math_ext", "least_uint_result"],
  ["math_ext", "ceil"],
  ["math_ext", "floor"],
  ["math_ext", "round"],
  ["math_ext", "trunc"],
  ["math_ext", "abs"],
  ["math_ext", "sign"],
  ["math_ext", "isNaN"],
  ["math_ext", "isInf"],
  ["math_ext", "isFinite"],
  ["math_ext", "bit_and"],
  ["math_ext", "bit_or"],
  ["math_ext", "bit_xor"],
  ["math_ext", "bit_not"],
  ["math_ext", "bit_shift_left"],
  ["math_ext", "bit_shift_right"],
  ["macros2"],
  ["optionals", "optionals"],
  ["proto2", "literal_singular", "int64_nocontainer"],
  ["proto2", "literal_singular", "int32"],
  ["proto2", "literal_singular", "int64"],
  ["proto2", "literal_singular", "uint32"],
  ["proto2", "literal_singular", "uint64"],
  ["proto2", "literal_singular", "sint32"],
  ["proto2", "literal_singular", "sint64"],
  ["proto2", "literal_singular", "fixed32"],
  ["proto2", "literal_singular", "fixed64"],
  ["proto2", "literal_singular", "sfixed32"],
  ["proto2", "literal_singular", "sfixed64"],
  ["proto2", "literal_singular", "float"],
  ["proto2", "literal_singular", "double"],
  ["proto2", "literal_singular", "bool"],
  ["proto2", "literal_singular", "string"],
  ["proto2", "literal_singular", "bytes"],
  ["proto2", "literal_wellknown"],
  ["proto2", "singular_bind"],
  ["proto2", "empty_field", "nested_message"],
  ["proto2", "empty_field", "map"],
  ["proto2", "set_null"],
  ["proto2", "quoted_fields"],
  ["proto2", "extensions_get"],
  ["proto2", "extensions_has"],
  ["proto2_ext"],
  ["proto3", "literal_singular"],
  ["proto3", "literal_wellknown"],
  ["proto3", "singular_bind"],
  ["proto3", "empty_field", "nested_message"],
  ["proto3", "empty_field", "map"],
  ["proto3", "set_null"],
  ["proto3", "quoted_fields"],
  ["string_ext", "format", "scientific notation formatting clause"],
  ["string_ext", "format", "default precision for scientific notation"],
  ["string_ext", "format", "map support for string"],
  ["string_ext", "format", "dyntype support for scientific notation"],
  [
    "string_ext",
    "format",
    "scientific notation formatting clause in a string variable",
  ],
  ["timestamps", "duration_conversions", "type_comparison"],
  ["timestamps", "timestamp_selectors", "getMilliseconds"],
  ["timestamps", "timestamp_conversions", "type_comparison"],
  ["type_deductions", "legacy_nullable_types"],
]);

void suite("Conformance Tests", () => {
  const typeRegistry = getTestRegistry();
  for (const file of files) {
    void testSimpleTestFile(file, typeRegistry, shouldSkip);
  }
});
