// Copyright 2024-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type { Overload } from "@bufbuild/cel-spec/enum/overload.js";

export function lookUpOverloadId(signature: string): string | undefined {
  return map[signature];
}

type ReverseOverloadMap = {
  [K in Overload]: string;
};

const reverseMap: ReverseOverloadMap = {
  conditional: "",
  logical_and: "",
  logical_or: "",
  logical_not: "@global.!_(bool): bool",
  not_strictly_false: "",
  equals: "@global._==_(dyn, dyn): bool",
  not_equals: "@global._!=_(dyn, dyn): bool",
  less_bool: "@global._<_(bool, bool): bool",
  less_int64: "@global._<_(int, int): bool",
  less_int64_double: "@global._<_(int, double): bool",
  less_int64_uint64: "@global._<_(int, uint): bool",
  less_uint64: "@global._<_(uint, uint): bool",
  less_uint64_double: "@global._<_(uint, double): bool",
  less_uint64_int64: "@global._<_(uint, int): bool",
  less_double: "@global._<_(double, double): bool",
  less_double_int64: "@global._<_(double, int): bool",
  less_double_uint64: "@global._<_(double, uint): bool",
  less_string: "@global._<_(string, string): bool",
  less_bytes: "@global._<_(bytes, bytes): bool",
  less_timestamp: "@global._<_(Timestamp, Timestamp): bool",
  less_duration: "@global._<_(Duration, Duration): bool",
  less_equals_bool: "@global._<=_(bool, bool): bool",
  less_equals_int64: "@global._<=_(int, int): bool",
  less_equals_int64_double: "@global._<=_(int, double): bool",
  less_equals_int64_uint64: "@global._<=_(int, uint): bool",
  less_equals_uint64: "@global._<=_(uint, uint): bool",
  less_equals_uint64_double: "@global._<=_(uint, double): bool",
  less_equals_uint64_int64: "@global._<=_(uint, int): bool",
  less_equals_double: "@global._<=_(double, double): bool",
  less_equals_double_int64: "@global._<=_(double, int): bool",
  less_equals_double_uint64: "@global._<=_(double, uint): bool",
  less_equals_string: "@global._<=_(string, string): bool",
  less_equals_bytes: "@global._<=_(bytes, bytes): bool",
  less_equals_timestamp: "@global._<=_(Timestamp, Timestamp): bool",
  less_equals_duration: "@global._<=_(Duration, Duration): bool",
  greater_bool: "@global._>_(bool, bool): bool",
  greater_int64: "@global._>_(int, int): bool",
  greater_int64_double: "@global._>_(int, double): bool",
  greater_int64_uint64: "@global._>_(int, uint): bool",
  greater_uint64: "@global._>_(uint, uint): bool",
  greater_uint64_double: "@global._>_(uint, double): bool",
  greater_uint64_int64: "@global._>_(uint, int): bool",
  greater_double: "@global._>_(double, double): bool",
  greater_double_int64: "@global._>_(double, int): bool",
  greater_double_uint64: "@global._>_(double, uint): bool",
  greater_string: "@global._>_(string, string): bool",
  greater_bytes: "@global._>_(bytes, bytes): bool",
  greater_timestamp: "@global._>_(Timestamp, Timestamp): bool",
  greater_duration: "@global._>_(Duration, Duration): bool",
  greater_equals_bool: "@global._>=_(bool, bool): bool",
  greater_equals_int64: "@global._>=_(int, int): bool",
  greater_equals_int64_double: "@global._>=_(int, double): bool",
  greater_equals_int64_uint64: "@global._>=_(int, uint): bool",
  greater_equals_uint64: "@global._>=_(uint, uint): bool",
  greater_equals_uint64_double: "@global._>=_(uint, double): bool",
  greater_equals_uint64_int64: "@global._>=_(uint, int): bool",
  greater_equals_double: "@global._>=_(double, double): bool",
  greater_equals_double_int64: "@global._>=_(double, int): bool",
  greater_equals_double_uint64: "@global._>=_(double, uint): bool",
  greater_equals_string: "@global._>=_(string, string): bool",
  greater_equals_bytes: "@global._>=_(bytes, bytes): bool",
  greater_equals_timestamp: "@global._>=_(Timestamp, Timestamp): bool",
  greater_equals_duration: "@global._>=_(Duration, Duration): bool",
  add_int64: "@global._+_(int, int): int",
  add_uint64: "@global._+_(uint, uint): uint",
  add_double: "@global._+_(double, double): double",
  add_string: "@global._+_(string, string): string",
  add_bytes: "@global._+_(bytes, bytes): bytes",
  add_list: "@global._+_(list(dyn), list(dyn)): list(dyn)",
  add_timestamp_duration: "@global._+_(Timestamp, Duration): Timestamp",
  add_duration_timestamp: "@global._+_(Duration, Timestamp): Timestamp",
  add_duration_duration: "@global._+_(Duration, Duration): Duration",
  subtract_int64: "@global._-_(int, int): int",
  subtract_uint64: "@global._-_(uint, uint): uint",
  subtract_double: "@global._-_(double, double): double",
  subtract_timestamp_timestamp: "@global._-_(Timestamp, Timestamp): Duration",
  subtract_timestamp_duration: "@global._-_(Timestamp, Duration): Timestamp",
  subtract_duration_duration: "@global._-_(Duration, Duration): Duration",
  multiply_int64: "@global._*_(int, int): int",
  multiply_uint64: "@global._*_(uint, uint): uint",
  multiply_double: "@global._*_(double, double): double",
  divide_int64: "@global._/_(int, int): int",
  divide_uint64: "@global._/_(uint, uint): uint",
  divide_double: "@global._/_(double, double): double",
  modulo_int64: "@global._%_(int, int): int",
  modulo_uint64: "@global._%_(uint, uint): uint",
  negate_int64: "@global.-_(int): int",
  negate_double: "@global.-_(double): double",
  index_list: "", // "@global._[_](list, dyn): dyn",
  index_map: "", // "@global._[_](map, dyn): dyn",
  index_message: "", // "@global._[_](message, dyn): dyn",
  in: "",
  in_list: "@global.@in(dyn, list(dyn)): bool",
  in_map: "@global.@in(dyn, map(dyn, dyn)): bool",
  in_message: "",
  size: "",
  size_string: "@global.size(string): int",
  size_bytes: "@global.size(bytes): int",
  size_list: "@global.size(list(dyn)): int",
  size_map: "@global.size(map(dyn, dyn)): int",
  string_size: "string.size(): int",
  bytes_size: "bytes.size(): int",
  list_size: "list(dyn).size(): int",
  map_size: "map(dyn, dyn).size(): int",
  contains: "",
  endsWith: "",
  matches: "",
  startsWith: "",
  strings_quote: "",
  contains_string: "string.contains(string): bool",
  ends_with_string: "string.endsWith(string): bool",
  matches_string: "string.matches(string): bool",
  starts_with_string: "string.startsWith(string): bool",
  string_format: "",
  getFullYear: "",
  getMonth: "",
  getDayOfYear: "",
  getDate: "",
  getDayOfMonth: "",
  getDayOfWeek: "",
  getHours: "",
  getMinutes: "",
  getSeconds: "",
  getMilliseconds: "",
  timestamp_to_year: "@global.getFullYear(Timestamp): int",
  timestamp_to_month: "@global.getMonth(Timestamp): int",
  timestamp_to_day_of_year: "@global.getDayOfYear(Timestamp): int",
  timestamp_to_day_of_month: "@global.getDate(Timestamp): int",
  timestamp_to_day_of_month_1_based: "@global.getDayOfMonth(Timestamp): int",
  timestamp_to_day_of_week: "@global.getDayOfWeek(Timestamp): int",
  timestamp_to_hours: "@global.getHours(Timestamp): int",
  timestamp_to_minutes: "@global.getMinutes(Timestamp): int",
  timestamp_to_seconds: "@global.getSeconds(Timestamp): int",
  timestamp_to_milliseconds: "@global.getMilliseconds(Timestamp): int",
  timestamp_to_year_with_tz: "@global.getFullYear(Timestamp, string): int",
  timestamp_to_month_with_tz: "@global.getMonth(Timestamp, string): int",
  timestamp_to_day_of_year_with_tz:
    "@global.getDayOfYear(Timestamp, string): int",
  timestamp_to_day_of_month_with_tz: "@global.getDate(Timestamp, string): int",
  timestamp_to_day_of_month_1_based_with_tz:
    "@global.getDayOfMonth(Timestamp, string): int",
  timestamp_to_day_of_week_with_tz:
    "@global.getDayOfWeek(Timestamp, string): int",
  timestamp_to_hours_with_tz: "@global.getHours(Timestamp, string): int",
  timestamp_to_minutes_with_tz: "@global.getMinutes(Timestamp, string): int",
  timestamp_to_seconds_tz: "@global.getSeconds(Timestamp, string): int",
  timestamp_to_milliseconds_with_tz:
    "@global.getMilliseconds(Timestamp, string): int",
  duration_to_hours: "@global.getHours(Duration): int",
  duration_to_minutes: "@global.getMinutes(Duration): int",
  duration_to_seconds: "@global.getSeconds(Duration): int",
  duration_to_milliseconds: "@global.getMilliseconds(Duration): int",
  int: "",
  uint: "",
  double: "",
  bool: "",
  string: "",
  bytes: "",
  timestamp: "",
  duration: "",
  type: "@global.type(dyn): type",
  dyn: "@global.dyn(dyn): dyn",
  int64_to_int64: "@global.int(int): int",
  uint64_to_int64: "@global.int(uint): int",
  double_to_int64: "@global.int(double): int",
  string_to_int64: "@global.int(string): int",
  timestamp_to_int64: "@global.int(Timestamp): int",
  duration_to_int64: "@global.int(Duration): int",
  uint64_to_uint64: "@global.uint(uint): uint",
  int64_to_uint64: "@global.uint(int): uint",
  double_to_uint64: "@global.uint(double): uint",
  string_to_uint64: "@global.uint(string): uint",
  double_to_double: "@global.double(double): double",
  int64_to_double: "@global.double(int): double",
  uint64_to_double: "@global.double(uint): double",
  string_to_double: "@global.double(string): double",
  bool_to_bool: "@global.bool(bool): bool",
  string_to_bool: "@global.bool(string): bool",
  bytes_to_bytes: "@global.bytes(bytes): bytes",
  string_to_bytes: "@global.bytes(string): bytes",
  string_to_string: "@global.string(string): string",
  bool_to_string: "@global.string(bool): string",
  int64_to_string: "@global.string(int): string",
  uint64_to_string: "@global.string(uint): string",
  double_to_string: "@global.string(double): string",
  bytes_to_string: "@global.string(bytes): string",
  timestamp_to_string: "@global.string(Timestamp): string",
  duration_to_string: "@global.string(Duration): string",
  timestamp_to_timestamp: "@global.timestamp(Timestamp): Timestamp",
  string_to_timestamp: "@global.timestamp(string): Timestamp",
  int64_to_timestamp: "@global.timestamp(int): Timestamp",
  duration_to_duration: "@global.duration(Duration): Duration",
  string_to_duration: "@global.duration(string): Duration",
  int64_to_duration: "@global.duration(int): Duration",
  to_dyn: "",
  "@iterator": "",
  "@hasNext": "",
  "@next": "",
};

const map = Object.fromEntries(
  Object.entries(reverseMap).map(([v, k]) => [k, v]),
);
