// GENERATED BY tools/scripts/genUnicodeTable.js; DO NOT EDIT.
// yarn node ./tools/scripts/genUnicodeTable.js > src/UnicodeTables.ts

import { UnicodeRangeTable } from "./UnicodeRangeTable.js";

let _B64_MAP: Uint8Array | null = null;
const getB64Map = (): Uint8Array => {
  if (!_B64_MAP) {
    _B64_MAP = new Uint8Array(256);
    const b =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-";
    for (let i = 0; i < 64; i++) {
      _B64_MAP[b.charCodeAt(i)] = i;
    }
  }
  return _B64_MAP;
};

const decodeVLQ = (str: string): number[] => {
  const b64 = getB64Map();
  const res: number[] = [];
  let value = 0,
    shift = 0;
  for (let i = 0; i < str.length; i++) {
    const digit = b64[str.charCodeAt(i)];
    value |= (digit & 0x1f) << shift;
    if ((digit & 0x20) === 0) {
      res.push(value);
      value = 0;
      shift = 0;
    } else {
      shift += 5;
    }
  }
  return res;
};

const decodeRanges = (str: string, isStride1: boolean): Uint32Array => {
  if (str.length === 0) return new Uint32Array(0);
  const res = decodeVLQ(str);
  const numRanges = isStride1 ? res.length / 2 : res.length / 3;
  const out = new Uint32Array(numRanges * 3);
  let current = 0,
    resIdx = 0;
  for (let i = 0; i < numRanges; i++) {
    current += res[resIdx++];
    out[i * 3] = current;
    current += res[resIdx++];
    out[i * 3 + 1] = current;
    out[i * 3 + 2] = isStride1 ? 1 : res[resIdx++];
  }
  return out;
};

const decodeOrbit = (str: string): Map<number, number> => {
  const res = decodeVLQ(str);
  const map = new Map<number, number>();
  let currentKey = 0;
  for (let i = 0; i < res.length; i += 2) {
    currentKey += res[i];
    map.set(currentKey, res[i + 1]);
  }
  return map;
};

// Merges two stride-encoded UnicodeRangeTables. Expands any stride>1
// ranges to individual codepoints, then coalesces contiguous runs.
const mergeRanges = (a: Uint32Array, b: Uint32Array): Uint32Array => {
  if (b.length === 0) return a;
  if (a.length === 0) return b;
  const points: [number, number][] = [];
  const push = (arr: Uint32Array): void => {
    for (let i = 0; i < arr.length; i += 3) {
      const lo = arr[i],
        hi = arr[i + 1],
        stride = arr[i + 2];
      if (stride === 1) {
        points.push([lo, hi]);
      } else {
        for (let cp = lo; cp <= hi; cp += stride) points.push([cp, cp]);
      }
    }
  };
  push(a);
  push(b);
  points.sort((x, y) => x[0] - y[0]);
  const merged: [number, number][] = [];
  for (const [lo, hi] of points) {
    const last = merged[merged.length - 1];
    if (last && last[1] + 1 >= lo) {
      if (hi > last[1]) last[1] = hi;
    } else {
      merged.push([lo, hi]);
    }
  }
  const out = new Uint32Array(merged.length * 3);
  for (let i = 0; i < merged.length; i++) {
    out[i * 3] = merged[i][0];
    out[i * 3 + 1] = merged[i][1];
    out[i * 3 + 2] = 1;
  }
  return out;
};

// Sweeps the codepoint space using a platform property-escape regex and
// returns stride-1 ranges. Surrogates are included — String.fromCodePoint
// returns the lone surrogate char and platform regex matches \p{Cs} on it.
const sweepPlatform = (pattern: string): Uint32Array => {
  const re = new RegExp(pattern, "u");
  const ranges: number[] = [];
  let start = -1;
  for (let cp = 0; cp <= 0x10ffff; cp++) {
    if (re.test(String.fromCodePoint(cp))) {
      if (start < 0) start = cp;
    } else if (start >= 0) {
      ranges.push(start, cp - 1, 1);
      start = -1;
    }
  }
  if (start >= 0) ranges.push(start, 0x10ffff, 1);
  return Uint32Array.from(ranges);
};

class LazyDecoder<V> {
  private readonly initializer: Record<string, () => V>;
  private readonly cache: Map<string, V | null>;
  constructor(initializer: Record<string, () => V>) {
    this.initializer = initializer;
    this.cache = new Map();
  }
  has(key: string): boolean {
    return key in this.initializer;
  }
  get(key: string): V | null {
    const cached = this.cache.get(key);
    if (cached !== undefined || this.cache.has(key)) {
      return cached ?? null;
    }
    const fn = this.initializer[key];
    const val = fn ? fn() : null;
    this.cache.set(key, val);
    return val;
  }
}

let _CASE_ORBIT: Map<number, number> | null = null;
const getCASE_ORBIT = (): Map<number, number> => {
  if (!_CASE_ORBIT) {
    _CASE_ORBIT = decodeOrbit(
      "rDqpII-LsD+0HGrpIsCxJzElODoODrOnByP-Mz+HTieNj-HCweD1fDxeB+9HBwfC1FE2eBxfBjeE1eDmpII0fjB4c+BgkHChkHKikHDjkHBkkHImkHZnkHhhGlkH9O70H-Io8HBp8HBq8HBr8HBs8HBt8HBu8HBv8HJ48HB58HB68HB78HB88HB98HB+8HB-8HJo9HBp9HBq9HBr9HBs9HBt9HBu9HBv9HM89HLlaFs+HQwcQwdQ8-HzJpdErCBlGgphBokHjMu+pBBv+pBDy+pBBz+pBB0+pBB1+pBw5Um4+BBl4+B68cg17CBh17CBi17CBj17CBk17CBl17CBm17CBn17CBo17CBp17CBq17CBr17CBs17CBt17CBu17CBv17CBw17CBx17CBy17CBz17CB017CB117CB217CB317CB417CD717CB817CB917CB+17CB-17CBg27CBh27CBi27CBj27CBk27CBl27CBm27CBn27CBo27CBp27CBq27CBr27CBs27CBt27CBu27CBv27CBw27CBx27CBy27CBz27C",
    );
  }
  return _CASE_ORBIT;
};

// Additions from Unicode 15.0 → 16.0 per stable general-category name.
// Merged unconditionally with platform sweep output; no-op on 16.0+ engines.
const _DELTA_CATEGORIES = /*#__PURE__*/ new LazyDecoder<Uint32Array>({
  L: () =>
    decodeRanges(
      "pkHBBh6iBCBNCBkvXzBB36BbBKWB9JCB8lBJBCDDClBBCaaCt-Bt-BBfBgkG68DBmoHdBjhDsBBz8HxmWxmWBcBDgwhCgwhCBsTB",
      false,
    ),
  LC: () => decodeRanges("pkHBh6iBCNC0rZVLV", true),
  Ll: () => decodeRanges("qkHj6iBj6iBO1sZ1sZBUB", false),
  Lm: () => decodeRanges("uqjChBhBx+XCBpBBB", false),
  Lo: () =>
    decodeRanges(
      "guhCzBB36BDBCzLzLBBB8lBJBCDDClBBCaaCt-Bt-BBfBgkG68DBmoHdBmhDnBB18HxmWxmWBcBDgwhCgwhCBsTB",
      false,
    ),
  Lu: () => decodeRanges("pkHi6iBi6iBBOOC0rZ0rZBUB", false),
  M: () =>
    decodeRanges(
      "3kCymhCymhCBDBvM8lB8lBBHBCDDCDBCEBCPPB47C47CkuQRB-lhBBB",
      false,
    ),
  Mc: () => decodeRanges("49kCCBIDDCDBCBBCvavaswSCB", false),
  Mn: () =>
    decodeRanges("3kCymhCymhCBDBvM-lB-lBBEBOECPBB47CkuQkuQBKBECB-lhBBB", false),
  N: () => decodeRanges("gqjCJnsCTtoBJ3pRJ3hDJ37XJ4nGJ", true),
  Nd: () => decodeRanges("gqjCJnsCTtoBJ3pRJ3hDJ37XJ4nGJ", true),
  P: () => decodeRanges("u6GBBwBvv8Bvv8BmzBBBCBBpgCssUssUBBBwkeAB", false),
  Pd: () => decodeRanges("urjCA", true),
  Po: () => decodeRanges("u6GBBwB1i+B1i+BBCCBpgCpgCssUCBwkeAB", false),
  S: () =>
    decodeRanges(
      "nhJCBz+CDBlPBBK-82B-82BBxzvBxzvBBuHBRzNB-vKJBFBBoOGGvBIIWDDKiHiHBjBB",
      false,
    ),
  Sm: () => decodeRanges("usjCB", true),
  So: () =>
    decodeRanges(
      "nhJCBz+CDBlPBBKxwmDxwmDBuHBRzNB-vKJBFBBoOGGvBIIWDDKiHiHBjBB",
      false,
    ),
});

// Additions from Unicode 15.0 → 16.0 per stable script name.
const _DELTA_SCRIPTS = /*#__PURE__*/ new LazyDecoder<Uint32Array>({
  Arabic: () => decodeRanges("3kCrxhCrxhCBBB4BAB", false),
  Balinese: () => decodeRanges("u6GBwBA", true),
  Common: () =>
    decodeRanges(
      "nhJCBz+CDBlPBBKxwmDxwmDB4HBHzNB-vKJBFBBoOGGvBIIWDDKiHiHBjBB",
      false,
    ),
  Cyrillic: () => decodeRanges("pkHB", true),
  Egyptian_Hieroglyphs: () => decodeRanges("gjtC68D", true),
  Han: () => decodeRanges("w-6FtT", true),
  Kawi: () => decodeRanges("66nCA", true),
  Khitan_Small_Script: () => decodeRanges("-njDA", true),
  Latin: () => decodeRanges("r+pBCNC", true),
  Myanmar: () => decodeRanges("w2lCT", true),
});

// Full tables for scripts added in Unicode 16.0. Engines < 16.0 throw
// SyntaxError on these names, so platform sweep is impossible.
const _NEW_SCRIPTS = /*#__PURE__*/ new LazyDecoder<UnicodeRangeTable>({
  Garay: () => new UnicodeRangeTable(decodeRanges("gqjClBEcJB", true)),
  Gurung_Khema: () => new UnicodeRangeTable(decodeRanges("go4C5B", true)),
  Kirat_Rai: () => new UnicodeRangeTable(decodeRanges("gq7C5B", true)),
  Ol_Onal: () => new UnicodeRangeTable(decodeRanges("wu5DqBFA", true)),
  Sunuwar: () => new UnicodeRangeTable(decodeRanges("g+mChBPJ", true)),
  Todhri: () => new UnicodeRangeTable(decodeRanges("guhCzB", true)),
  Tulu_Tigalari: () =>
    new UnicodeRangeTable(
      decodeRanges("g8kCJBCDDClBBCJBCDDCDBCJBCBBJBB", false),
    ),
});

const STABLE_CATEGORY_NAMES: ReadonlySet<string> = new Set([
  "C",
  "Cc",
  "Cf",
  "Cn",
  "Co",
  "Cs",
  "L",
  "LC",
  "Ll",
  "Lm",
  "Lo",
  "Lt",
  "Lu",
  "M",
  "Mc",
  "Me",
  "Mn",
  "N",
  "Nd",
  "Nl",
  "No",
  "P",
  "Pc",
  "Pd",
  "Pe",
  "Pf",
  "Pi",
  "Po",
  "Ps",
  "S",
  "Sc",
  "Sk",
  "Sm",
  "So",
  "Z",
  "Zl",
  "Zp",
  "Zs",
]);
const STABLE_SCRIPT_NAMES: ReadonlySet<string> = new Set([
  "Adlam",
  "Ahom",
  "Anatolian_Hieroglyphs",
  "Arabic",
  "Armenian",
  "Avestan",
  "Balinese",
  "Bamum",
  "Bassa_Vah",
  "Batak",
  "Bengali",
  "Bhaiksuki",
  "Bopomofo",
  "Brahmi",
  "Braille",
  "Buginese",
  "Buhid",
  "Canadian_Aboriginal",
  "Carian",
  "Caucasian_Albanian",
  "Chakma",
  "Cham",
  "Cherokee",
  "Chorasmian",
  "Common",
  "Coptic",
  "Cuneiform",
  "Cypriot",
  "Cypro_Minoan",
  "Cyrillic",
  "Deseret",
  "Devanagari",
  "Dives_Akuru",
  "Dogra",
  "Duployan",
  "Egyptian_Hieroglyphs",
  "Elbasan",
  "Elymaic",
  "Ethiopic",
  "Georgian",
  "Glagolitic",
  "Gothic",
  "Grantha",
  "Greek",
  "Gujarati",
  "Gunjala_Gondi",
  "Gurmukhi",
  "Han",
  "Hangul",
  "Hanifi_Rohingya",
  "Hanunoo",
  "Hatran",
  "Hebrew",
  "Hiragana",
  "Imperial_Aramaic",
  "Inherited",
  "Inscriptional_Pahlavi",
  "Inscriptional_Parthian",
  "Javanese",
  "Kaithi",
  "Kannada",
  "Katakana",
  "Kawi",
  "Kayah_Li",
  "Kharoshthi",
  "Khitan_Small_Script",
  "Khmer",
  "Khojki",
  "Khudawadi",
  "Lao",
  "Latin",
  "Lepcha",
  "Limbu",
  "Linear_A",
  "Linear_B",
  "Lisu",
  "Lycian",
  "Lydian",
  "Mahajani",
  "Makasar",
  "Malayalam",
  "Mandaic",
  "Manichaean",
  "Marchen",
  "Masaram_Gondi",
  "Medefaidrin",
  "Meetei_Mayek",
  "Mende_Kikakui",
  "Meroitic_Cursive",
  "Meroitic_Hieroglyphs",
  "Miao",
  "Modi",
  "Mongolian",
  "Mro",
  "Multani",
  "Myanmar",
  "Nabataean",
  "Nag_Mundari",
  "Nandinagari",
  "New_Tai_Lue",
  "Newa",
  "Nko",
  "Nushu",
  "Nyiakeng_Puachue_Hmong",
  "Ogham",
  "Ol_Chiki",
  "Old_Hungarian",
  "Old_Italic",
  "Old_North_Arabian",
  "Old_Permic",
  "Old_Persian",
  "Old_Sogdian",
  "Old_South_Arabian",
  "Old_Turkic",
  "Old_Uyghur",
  "Oriya",
  "Osage",
  "Osmanya",
  "Pahawh_Hmong",
  "Palmyrene",
  "Pau_Cin_Hau",
  "Phags_Pa",
  "Phoenician",
  "Psalter_Pahlavi",
  "Rejang",
  "Runic",
  "Samaritan",
  "Saurashtra",
  "Sharada",
  "Shavian",
  "Siddham",
  "SignWriting",
  "Sinhala",
  "Sogdian",
  "Sora_Sompeng",
  "Soyombo",
  "Sundanese",
  "Syloti_Nagri",
  "Syriac",
  "Tagalog",
  "Tagbanwa",
  "Tai_Le",
  "Tai_Tham",
  "Tai_Viet",
  "Takri",
  "Tamil",
  "Tangsa",
  "Tangut",
  "Telugu",
  "Thaana",
  "Thai",
  "Tibetan",
  "Tifinagh",
  "Tirhuta",
  "Toto",
  "Ugaritic",
  "Unknown",
  "Vai",
  "Vithkuqi",
  "Wancho",
  "Warang_Citi",
  "Yezidi",
  "Yi",
  "Zanabazar_Square",
]);
const NEW_SCRIPT_NAMES: ReadonlySet<string> = new Set([
  "Garay",
  "Gurung_Khema",
  "Kirat_Rai",
  "Ol_Onal",
  "Sunuwar",
  "Todhri",
  "Tulu_Tigalari",
]);

const _sweepCache = new Map<string, UnicodeRangeTable>();
const _foldCache = new Map<string, UnicodeRangeTable | null>();

// Returns the base range table for a property name, or null if unknown.
// Stable names: platform sweep + bundled delta (15.0 → 16.0).
// New-in-16.0 script names: bundled full table.
const buildForProperty = (name: string): UnicodeRangeTable | null => {
  if (NEW_SCRIPT_NAMES.has(name)) {
    return _NEW_SCRIPTS.get(name);
  }
  let kind: "category" | "script" | null = null;
  let pattern: string | null = null;
  if (STABLE_CATEGORY_NAMES.has(name)) {
    kind = "category";
    pattern = `\\p{General_Category=${name}}`;
  } else if (STABLE_SCRIPT_NAMES.has(name)) {
    kind = "script";
    pattern = `\\p{Script=${name}}`;
  } else return null;

  const cacheKey = `${kind}:${name}`;
  const cached = _sweepCache.get(cacheKey);
  if (cached) return cached;

  const base = sweepPlatform(pattern);
  const delta =
    kind === "category"
      ? _DELTA_CATEGORIES.get(name)
      : _DELTA_SCRIPTS.get(name);
  const merged = delta ? mergeRanges(base, delta) : base;
  const table = new UnicodeRangeTable(merged);
  _sweepCache.set(cacheKey, table);
  return table;
};

// Computes the fold-overlay for a property name: additional runes that
// fold to some rune already in the base class. Returns null if no overlay
// is needed (base class is fold-stable).
const buildFoldOverlay = (name: string): UnicodeRangeTable | null => {
  const cached = _foldCache.get(name);
  if (cached !== undefined) return cached;
  const base = buildForProperty(name);
  if (!base) {
    _foldCache.set(name, null);
    return null;
  }
  const inBase = (r: number): boolean => {
    let lo = 0,
      hi = base.length;
    while (lo < hi) {
      const m = (lo + hi) >> 1;
      const rlo = base.getLo(m),
        rhi = base.getHi(m);
      if (r < rlo) hi = m;
      else if (r > rhi) lo = m + 1;
      else return (r - rlo) % base.getStride(m) === 0;
    }
    return false;
  };
  // Inline simpleFold to avoid circular import with Unicode.ts.
  const orbit = getCASE_ORBIT();
  const simpleFold = (r: number): number => {
    const folded = orbit.get(r);
    if (folded !== undefined) return folded;
    const s = String.fromCodePoint(r);
    const lower = s.toLowerCase();
    if (lower.length === s.length) {
      const lowerCp = lower.codePointAt(0);
      if (lowerCp !== undefined && lowerCp !== r) return lowerCp;
    }
    const upper = s.toUpperCase();
    if (upper.length === s.length) {
      const upperCp = upper.codePointAt(0);
      if (upperCp !== undefined && upperCp !== r) return upperCp;
    }
    return r;
  };
  const extras = new Set<number>();
  for (let i = 0; i < base.length; i++) {
    const lo = base.getLo(i),
      hi = base.getHi(i),
      stride = base.getStride(i);
    for (let cp = lo; cp <= hi; cp += stride) {
      let r = simpleFold(cp);
      while (r !== cp) {
        if (!inBase(r)) extras.add(r);
        r = simpleFold(r);
      }
    }
  }
  if (extras.size === 0) {
    _foldCache.set(name, null);
    return null;
  }
  const sorted = Array.from(extras).sort((a, b) => a - b);
  const merged: [number, number][] = [];
  for (const cp of sorted) {
    const last = merged[merged.length - 1];
    if (last && last[1] + 1 === cp) last[1] = cp;
    else merged.push([cp, cp]);
  }
  const out = new Uint32Array(merged.length * 3);
  for (let i = 0; i < merged.length; i++) {
    out[i * 3] = merged[i][0];
    out[i * 3 + 1] = merged[i][1];
    out[i * 3 + 2] = 1;
  }
  const table = new UnicodeRangeTable(out);
  _foldCache.set(name, table);
  return table;
};

const getUpper = (): UnicodeRangeTable => {
  const table = buildForProperty("Lu");
  if (table === null) {
    throw new Error("Upper: missing Lu property");
  }
  return table;
};

// --- Legacy API surface used by Parser ---

export const UnicodeTables = {
  get CASE_ORBIT(): Map<number, number> {
    return getCASE_ORBIT();
  },
  STABLE_CATEGORY_NAMES,
  STABLE_SCRIPT_NAMES,
  NEW_SCRIPT_NAMES,
  buildForProperty,
  buildFoldOverlay,
  CATEGORIES: {
    has: (name: string): boolean => STABLE_CATEGORY_NAMES.has(name),
    get: (name: string): UnicodeRangeTable | null => buildForProperty(name),
  },
  SCRIPTS: {
    has: (name: string): boolean =>
      STABLE_SCRIPT_NAMES.has(name) || NEW_SCRIPT_NAMES.has(name),
    get: (name: string): UnicodeRangeTable | null => buildForProperty(name),
  },
  FOLD_CATEGORIES: {
    has: (name: string): boolean => STABLE_CATEGORY_NAMES.has(name),
    get: (name: string): UnicodeRangeTable | null => buildFoldOverlay(name),
  },
  FOLD_SCRIPT: {
    has: (name: string): boolean =>
      STABLE_SCRIPT_NAMES.has(name) || NEW_SCRIPT_NAMES.has(name),
    get: (name: string): UnicodeRangeTable | null => buildFoldOverlay(name),
  },
  get Upper(): UnicodeRangeTable {
    return getUpper();
  },

  // --- Test-only hooks: expose the raw bundled 15.0→16.0 delta and
  // new-in-16.0 script data so tests can verify the generator output.
  // These are not part of the public API.
  _deltaCategoryRanges: (name: string): Uint32Array | null =>
    _DELTA_CATEGORIES.get(name),
  _deltaScriptRanges: (name: string): Uint32Array | null =>
    _DELTA_SCRIPTS.get(name),
  _newScriptTable: (name: string): UnicodeRangeTable | null =>
    _NEW_SCRIPTS.get(name),
};
