name: ci
on:
  push:
    branches: [main, "v*"]
    tags: ["v*"]
  pull_request:
    branches: [main, "v*"]
  workflow_dispatch:

permissions:
  contents: read

env:
  # https://consoledonottrack.com/
  DO_NOT_TRACK: 1

jobs:
  all:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    name: "Node.js ${{ matrix.node-version }}"
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: protobuf-es/test/${{ github.sha }}
          restore-keys: protobuf-es/test
      - run: npm ci
      - run: npm run all
      - run: node scripts/gh-diffcheck.js
